version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://artisticai:password@db:5432/artisticai_db
    networks:
      - artisticai_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=artisticai
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=artisticai_db
    networks:
      - artisticai_network

volumes:
  postgres_data:

networks:
  artisticai_network:
    driver: bridge
