[tox]
envlist = py38, py39, flake8
isolated_build = True

[testenv]
deps =
    pytest
    -r{toxinidir}/requirements.txt
commands =
    pytest

[testenv:flake8]
basepython = python3.8
deps =
    flake8
commands =
    flake8 artisticai tests

[flake8]
max-line-length = 120
exclude = .tox,*.egg,build,data
select = E,W,F
